// Andere namen die bij het nakijken van de oefentoets ook goed zijn, en namen die
// erop lijken maar een andere plek zijn. Zie src/game/toets.ts.

/** Per plek (zoals die in de lijst heet): andere schrijfwijzen die ook goed zijn. */
export const ALIASES: Record<string, string[]> = {
  'Democratische Republiek Kongo': ['Kongo', 'Congo', 'DR Kongo', 'DR Congo', 'Congo-Kinshasa'],
  'Verenigde Staten': ['VS', 'USA', 'Amerika', 'Verenigde Staten van Amerika'],
  Engeland: ['Groot-Brittannië', 'Verenigd Koninkrijk', 'UK'],
  'Saudi-Arabië': ['Saoedi-Arabië'],
  Filipijnen: ['Filippijnen', 'De Filipijnen'],
  'Papoea-Nieuw-Guinea': ['Papua-Nieuw-Guinea', 'Nieuw-Guinea'],
  Rusland: ['Russische Federatie'],
  Nederland: ['Holland'],
  'Zuid-Afrika': ['Zuid-Afrikaanse Republiek'],
  Oekraïne: ['Ukraine'],
  Myanmar: ['Birma', 'Burma'],
  Haïti: ['Haiti'],
};

/**
 * Landen die niet in de lijst staan maar op een land uit de lijst lijken (Niger
 * naast Nigeria, Oostenrijk naast Australië). Schrijft een kind zo'n naam op, dan
 * is dat geen spelfout maar een ander land.
 */
export const LOOKALIKES: string[] = [
  'Niger',
  'Mali',
  'Malawi',
  'Guinee',
  'Equatoriaal-Guinea',
  'Gambia',
  'Zambia',
  'Namibië',
  'Nigeria',
  'Liberia',
  'Libanon',
  'Jordanië',
  'Oman',
  'Koeweit',
  'Bahrein',
  'Verenigde Arabische Emiraten',
  'Tsjaad',
  'Kameroen',
  'Gabon',
  'Congo-Brazzaville',
  'Oeganda',
  'Rwanda',
  'Mozambique',
  'Zimbabwe',
  'Botswana',
  'Eritrea',
  'Mauritanië',
  'Zwitserland',
  'Zweden',
  'België',
  'Denemarken',
  'Polen',
  'Portugal',
  'Ierland',
  'IJsland',
  'Schotland',
  'Wales',
  'Oostenrijk',
  'Australië',
  'Roemenië',
  'Bulgarije',
  'Albanië',
  'Armenië',
  'Georgië',
  'Slowakije',
  'Slovenië',
  'Servië',
  'Kroatië',
  'Estland',
  'Letland',
  'Litouwen',
  'Wit-Rusland',
  'Turkmenistan',
  'Oezbekistan',
  'Tadzjikistan',
  'Kirgizië',
  'Nepal',
  'Bangladesh',
  'Sri Lanka',
  'Laos',
  'Cambodja',
  'Taiwan',
  'Singapore',
  'Guatemala',
  'Honduras',
  'Nicaragua',
  'Costa Rica',
  'Dominicaanse Republiek',
  'Guyana',
  'Frans-Guyana',
  'Groenland',
  'Paraguay',
  'Uruguay',
  'Palestina',
  'Cyprus',
];
