// Alle onderdelen van de categorie "Wateren en landschappen over de wereld",
// met per onderdeel waar de vorm vandaan komt in Natural Earth (1:10 miljoen).
// Gebruikt door build.mjs; de volgorde binnen een pakket is die van de lijst
// van de eigenaar.
//
// Soorten (kind):
//   sea       oceaan, zee, golf of baai: vlak, getekend onder het land
//   lake      meer: vlak op het land
//   river     rivier: lijn
//   desert    woestijn: vlak op het land
//   range     gebergte: vlak op het land
//   peak      berg: punt (precieze top)
//   trench    trog in de oceaanbodem: vlak boven de zee
//
// hint: wat er bij een hint in beeld komt ("Tip: ...").
// anchor: [breedte, lengte] voor het label/knipperpunt; zonder anchor wordt
// een punt midden in de vorm berekend.

export const items = [
  // Pakket 1
  {
    name: 'Grote Oceaan',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'tussen Azië, Australië en Amerika',
    anchor: [8, -150],
    marine: [
      'North Pacific Ocean',
      'South Pacific Ocean',
      'Philippine Sea',
      'Sea of Japan',
      'East China Sea',
      'Yellow Sea',
      'Bo Hai',
      'Sea of Okhotsk',
      'Gulf of Alaska',
      'Golfo de California',
      'Solomon Sea',
      'Bismarck Sea',
    ],
  },
  {
    name: 'Atlantische Oceaan',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'tussen Amerika, Europa en Afrika',
    anchor: [25, -40],
    marine: [
      'North Atlantic Ocean',
      'South Atlantic Ocean',
      'Sargasso Sea',
      'Labrador Sea',
      'Norwegian Sea',
      'Bay of Biscay',
      'Irish Sea',
      'English Channel',
      'Gulf of Guinea',
      'Baffin Bay',
      'Davis Strait',
      'Denmark Strait',
    ],
  },
  {
    name: 'Indische Oceaan',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'tussen Afrika, Azië en Australië',
    anchor: [-22, 78],
    marine: [
      'INDIAN OCEAN',
      'Andaman Sea',
      'Laccadive Sea',
      'Great Australian Bight',
      'Mozambique Channel',
      'Timor Sea',
    ],
  },
  {
    name: 'Noordelijke IJszee',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'rond de Noordpool',
    anchor: [80, 150],
    marine: [
      'Arctic Ocean',
      'Kara Sea',
      'Laptev Sea',
      'East Siberian Sea',
      'Chukchi Sea',
      'Beaufort Sea',
      'Lincoln Sea',
      'Greenland Sea',
    ],
  },
  {
    name: 'Middellandse Zee',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'tussen Europa en Afrika',
    marine: [
      'Mediterranean Sea',
      'Adriatic Sea',
      'Aegean Sea',
      'Alboran Sea',
      'Balearic Sea',
      'Ionian Sea',
      'Ligurian Sea',
      'Tyrrhenian Sea',
      'Sea of Crete',
      'Golfe du Lion',
      'Sea of Marmara',
      'Dardanelles',
    ],
  },
  {
    name: 'Golf van Mexico',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'Noord-Amerika',
    marine: ['Gulf of Mexico', 'Bahía de Campeche'],
  },
  {
    name: 'Arabische Zee',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'Azië, tussen Arabië en India',
    marine: ['Arabian Sea', 'Gulf of Oman', 'Gulf of Aden'],
  },
  {
    name: 'Zuid-Chinese Zee',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'Azië',
    marine: ['South China Sea', 'Gulf of Thailand', 'Gulf of Tonkin'],
  },
  {
    name: 'Rode Zee',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'tussen Afrika en Azië',
    marine: ['Red Sea', 'Gulf of Aqaba', 'Gulf of Suez'],
  },
  {
    name: 'Perzische Golf',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'Azië (Midden-Oosten)',
    marine: ['Persian Gulf'],
  },
  {
    name: 'Beringzee',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'tussen Azië en Noord-Amerika',
    marine: ['Bering Sea', "Gulf of Anadyr'", 'Bristol Bay', 'Norton Sound'],
  },
  {
    name: 'Koraalzee',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'bij Australië',
    marine: ['Coral Sea', 'Gulf of Papua'],
  },
  {
    name: 'Barentszee',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'ten noorden van Europa',
    marine: ['Barents Sea', 'White Sea'],
  },
  {
    name: 'Hudsonbaai',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'Noord-Amerika',
    marine: ['Hudson Bay', 'James Bay'],
  },
  { name: 'Noordzee', pkg: 'wateren1', kind: 'sea', hint: 'Europa', marine: ['North Sea'] },
  { name: 'Donau', pkg: 'wateren1', kind: 'river', hint: 'Europa', rivers: ['Danube', 'Donau'] },
  {
    name: 'Nijl',
    pkg: 'wateren1',
    kind: 'river',
    hint: 'Afrika',
    rivers: [
      'Nile',
      'El Bahr el Abyad',
      'Bahr el Jebel',
      'Albert Nile',
      'Victoria Nile',
      'El Bahr el Azraq',
    ],
  },
  { name: 'Amazone', pkg: 'wateren1', kind: 'river', hint: 'Zuid-Amerika', rivers: ['Amazonas'] },
  { name: 'Wolga', pkg: 'wateren1', kind: 'river', hint: 'Europa', rivers: ['Volga'] },
  { name: 'Ganges', pkg: 'wateren1', kind: 'river', hint: 'Azië', rivers: ['Ganges'] },
  {
    name: 'Chang Jiang',
    pkg: 'wateren1',
    kind: 'river',
    hint: 'Azië',
    rivers: ['Chang Jiang', 'Yangtze'],
  },
  {
    name: 'Mississippi',
    pkg: 'wateren1',
    kind: 'river',
    hint: 'Noord-Amerika',
    rivers: ['Mississippi'],
  },
  { name: 'Paraná', pkg: 'wateren1', kind: 'river', hint: 'Zuid-Amerika', rivers: ['Paraná'] },
  { name: 'Eufraat', pkg: 'wateren1', kind: 'river', hint: 'Azië', rivers: ['Euphrates'] },
  { name: 'Rijn', pkg: 'wateren1', kind: 'river', hint: 'Europa', rivers: ['Rhine', 'Rhein'] },
  {
    name: 'Zwarte Zee',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'tussen Europa en Azië',
    marine: ['Black Sea', 'Sea of Azov'],
  },
  {
    name: 'Kaspische Zee',
    pkg: 'wateren1',
    kind: 'sea',
    hint: 'tussen Europa en Azië',
    marine: ['Caspian Sea'],
  },
  { name: 'Victoriameer', pkg: 'wateren1', kind: 'lake', hint: 'Afrika', lakes: ['Lake Victoria'] },
  {
    name: 'Titicacameer',
    pkg: 'wateren1',
    kind: 'lake',
    hint: 'Zuid-Amerika',
    lakes: ['Lago Titicaca'],
  },
  { name: 'Bajkalmeer', pkg: 'wateren1', kind: 'lake', hint: 'Azië', lakes: ['Lake Baikal'] },
  { name: 'Sahara', pkg: 'wateren1', kind: 'desert', hint: 'Afrika', regions: ['SAHARA'] },
  {
    name: 'Kalahari',
    pkg: 'wateren1',
    kind: 'desert',
    hint: 'Afrika',
    regions: ['KALAHARI DESERT'],
  },
  { name: 'Himalaya', pkg: 'wateren1', kind: 'range', hint: 'Azië', regions: ['HIMALAYAS'] },
  {
    name: 'Rocky Mountains',
    pkg: 'wateren1',
    kind: 'range',
    hint: 'Noord-Amerika',
    regions: ['ROCKY MOUNTAINS'],
  },
  {
    name: 'Andesgebergte',
    pkg: 'wateren1',
    kind: 'range',
    hint: 'Zuid-Amerika',
    regions: ['ANDES'],
  },
  {
    name: 'Appalachen',
    pkg: 'wateren1',
    kind: 'range',
    hint: 'Noord-Amerika',
    regions: ['APPALACHIAN MTS.'],
  },
  { name: 'Alpen', pkg: 'wateren1', kind: 'range', hint: 'Europa', regions: ['ALPS'] },
  { name: 'Mount Everest', pkg: 'wateren1', kind: 'peak', hint: 'Azië', peak: [27.9883, 86.9253] },
  {
    name: 'Aconcagua',
    pkg: 'wateren1',
    kind: 'peak',
    hint: 'Zuid-Amerika',
    peak: [-32.6533, -70.0108],
  },
  { name: 'Kilimanjaro', pkg: 'wateren1', kind: 'peak', hint: 'Afrika', peak: [-3.0758, 37.3533] },

  // Pakket 2
  {
    name: 'Oostzee',
    pkg: 'wateren2',
    kind: 'sea',
    hint: 'Europa',
    marine: ['Baltic Sea', 'Gulf of Bothnia', 'Gulf of Finland', 'Gulf of Riga', 'Kattegat'],
  },
  {
    name: 'Tasmanzee',
    pkg: 'wateren2',
    kind: 'sea',
    hint: 'bij Australië',
    marine: ['Tasman Sea'],
  },
  { name: 'Lena', pkg: 'wateren2', kind: 'river', hint: 'Azië', rivers: ['Lena'] },
  { name: 'Zambezi', pkg: 'wateren2', kind: 'river', hint: 'Afrika', rivers: ['Zambezi'] },
  { name: 'Tigris', pkg: 'wateren2', kind: 'river', hint: 'Azië', rivers: ['Tigris'] },
  {
    name: 'Atlasgebergte',
    pkg: 'wateren2',
    kind: 'range',
    hint: 'Afrika',
    regions: ['ATLAS MOUNTAINS'],
  },
  {
    name: 'Oeralgebergte',
    pkg: 'wateren2',
    kind: 'range',
    hint: 'tussen Europa en Azië',
    regions: ['URAL MOUNTAINS'],
  },
  { name: 'Mont Blanc', pkg: 'wateren2', kind: 'peak', hint: 'Europa', peak: [45.8328, 6.865] },
  {
    name: 'Mount McKinley',
    pkg: 'wateren2',
    kind: 'peak',
    hint: 'Noord-Amerika',
    peak: [63.069, -151.0063],
  },
  { name: 'K2', pkg: 'wateren2', kind: 'peak', hint: 'Azië', peak: [35.8825, 76.5133] },

  // Pakket 3
  {
    name: 'Golf van Bengalen',
    pkg: 'wateren3',
    kind: 'sea',
    hint: 'Azië',
    marine: ['Bay of Bengal'],
  },
  {
    name: 'Caribische Zee',
    pkg: 'wateren3',
    kind: 'sea',
    hint: 'Midden-Amerika',
    marine: ['Caribbean Sea', 'Gulf of Honduras'],
  },
  { name: 'Ob', pkg: 'wateren3', kind: 'river', hint: 'Azië', rivers: ['Ob'] },
  { name: 'Huang He', pkg: 'wateren3', kind: 'river', hint: 'Azië', rivers: ['Huang'] },
  {
    name: 'Bovenmeer',
    pkg: 'wateren3',
    kind: 'lake',
    hint: 'Noord-Amerika',
    lakes: ['Lake Superior'],
  },
  {
    name: 'Michiganmeer',
    pkg: 'wateren3',
    kind: 'lake',
    hint: 'Noord-Amerika',
    lakes: ['Lake Michigan'],
  },
  { name: 'Pyreneeën', pkg: 'wateren3', kind: 'range', hint: 'Europa', regions: ['PYRENEES'] },
  {
    name: 'Karpaten',
    pkg: 'wateren3',
    kind: 'range',
    hint: 'Europa',
    regions: ['CARPATHIAN MOUNTAINS'],
  },
  {
    name: 'Mount Cook',
    pkg: 'wateren3',
    kind: 'peak',
    hint: 'Oceanië',
    peak: [-43.5956, 170.1408],
  },
  { name: 'Elbrus', pkg: 'wateren3', kind: 'peak', hint: 'Europa', peak: [43.3531, 42.4369] },

  // Pakket 4
  {
    name: 'Huronmeer',
    pkg: 'wateren4',
    kind: 'lake',
    hint: 'Noord-Amerika',
    lakes: ['Lake Huron'],
  },
  { name: 'Eriemeer', pkg: 'wateren4', kind: 'lake', hint: 'Noord-Amerika', lakes: ['Lake Erie'] },
  {
    name: 'Ontariomeer',
    pkg: 'wateren4',
    kind: 'lake',
    hint: 'Noord-Amerika',
    lakes: ['Lake Ontario'],
  },
  { name: 'Indus', pkg: 'wateren4', kind: 'river', hint: 'Azië', rivers: ['Indus'] },
  { name: 'Yukon', pkg: 'wateren4', kind: 'river', hint: 'Noord-Amerika', rivers: ['Yukon'] },
  { name: 'Kongorivier', pkg: 'wateren4', kind: 'river', hint: 'Afrika', rivers: ['Congo'] },
  {
    // Uit de dieptekaart van Natural Earth: de stukken zeebodem dieper dan 6000 m langs
    // de Marianen, alleen als er ook een plek dieper dan 7000 m in ligt (dat is alleen
    // de trog zelf). Ankerpunt: Challengerdiepte, het diepste punt op aarde.
    name: 'Marianentrog',
    pkg: 'wateren4',
    kind: 'trench',
    hint: 'Grote Oceaan',
    anchor: [11.37, 142.4],
    trench: { box: [140.5, 10, 149, 25.5] },
  },
  { name: 'Gobiwoestijn', pkg: 'wateren4', kind: 'desert', hint: 'Azië', regions: ['GOBI DESERT'] },
  { name: 'Ararat', pkg: 'wateren4', kind: 'peak', hint: 'Azië', peak: [39.7017, 44.2983] },
  { name: 'Mulhacén', pkg: 'wateren4', kind: 'peak', hint: 'Europa', peak: [37.0533, -3.3114] },
];

/**
 * Zeeën die bij geen enkel onderdeel horen en ook niet automatisch bij een
 * buurzee mogen worden gevoegd (twijfelgevallen en de Zuidelijke Oceaan).
 * Klikken daar doet niets.
 */
export const neutralMarine = [
  'SOUTHERN OCEAN',
  'Weddell Sea',
  'Ross Sea',
  'Amundsen Sea',
  'Bellingshausen Sea',
  'Davis Sea',
  'Scotia Sea',
  'Drake Passage',
  'Bransfield Strait',
  'George VI Sound',
  'Java Sea',
  'Flores Sea',
  'Bali Sea',
  'Savu Sea',
  'Banda Sea',
  'Molucca Sea',
  'Halmahera Sea',
  'Ceram Sea',
  'Celebes Sea',
  'Sulu Sea',
  'Bohol Sea',
  'Samar Sea',
  'Sibuyan Sea',
  'Visayan Sea',
  'Arafura Sea',
  'Gulf of Carpentaria',
  'Garabogaz Bay',
  // Een meer (lagune) in Venezuela, geen deel van de Caribische Zee.
  'Lago de Maracaibo',
];
