// De lijst van "Vlaggen van de wereld": alle 193 landen van de Verenigde Naties,
// plus Vaticaanstad en Kosovo (keuze eigenaar: alle landen, per werelddeel).
// Na aanpassen: node scripts/vlaggen/build.mjs
//
// Per land: Nederlandse naam en de landcode (ISO 3166-1 alpha-2) voor de vlag en de
// kaart. Turkije, Georgië, Armenië, Azerbeidzjan en Kazachstan staan bij Azië;
// Rusland en Cyprus bij Europa.

export const continents = [
  { id: 'vlaggen-europa', name: 'Europa' },
  { id: 'vlaggen-afrika', name: 'Afrika' },
  { id: 'vlaggen-azie', name: 'Azië' },
  { id: 'vlaggen-noord-amerika', name: 'Noord- en Midden-Amerika' },
  { id: 'vlaggen-zuid-amerika', name: 'Zuid-Amerika' },
  { id: 'vlaggen-oceanie', name: 'Oceanië' },
];

const europa = [
  ['Albanië', 'al'],
  ['Andorra', 'ad'],
  ['België', 'be'],
  ['Bosnië en Herzegovina', 'ba'],
  ['Bulgarije', 'bg'],
  ['Cyprus', 'cy'],
  ['Denemarken', 'dk'],
  ['Duitsland', 'de'],
  ['Estland', 'ee'],
  ['Finland', 'fi'],
  ['Frankrijk', 'fr'],
  ['Griekenland', 'gr'],
  ['Hongarije', 'hu'],
  ['Ierland', 'ie'],
  ['IJsland', 'is'],
  ['Italië', 'it'],
  ['Kosovo', 'xk'],
  ['Kroatië', 'hr'],
  ['Letland', 'lv'],
  ['Liechtenstein', 'li'],
  ['Litouwen', 'lt'],
  ['Luxemburg', 'lu'],
  ['Malta', 'mt'],
  ['Moldavië', 'md'],
  ['Monaco', 'mc'],
  ['Montenegro', 'me'],
  ['Nederland', 'nl'],
  ['Noord-Macedonië', 'mk'],
  ['Noorwegen', 'no'],
  ['Oekraïne', 'ua'],
  ['Oostenrijk', 'at'],
  ['Polen', 'pl'],
  ['Portugal', 'pt'],
  ['Roemenië', 'ro'],
  ['Rusland', 'ru'],
  ['San Marino', 'sm'],
  ['Servië', 'rs'],
  ['Slovenië', 'si'],
  ['Slowakije', 'sk'],
  ['Spanje', 'es'],
  ['Tsjechië', 'cz'],
  ['Vaticaanstad', 'va'],
  ['Verenigd Koninkrijk', 'gb'],
  ['Wit-Rusland', 'by'],
  ['Zweden', 'se'],
  ['Zwitserland', 'ch'],
];

const afrika = [
  ['Algerije', 'dz'],
  ['Angola', 'ao'],
  ['Benin', 'bj'],
  ['Botswana', 'bw'],
  ['Burkina Faso', 'bf'],
  ['Burundi', 'bi'],
  ['Centraal-Afrikaanse Republiek', 'cf'],
  ['Comoren', 'km'],
  ['Congo-Brazzaville', 'cg'],
  ['Democratische Republiek Kongo', 'cd'],
  ['Djibouti', 'dj'],
  ['Egypte', 'eg'],
  ['Equatoriaal-Guinea', 'gq'],
  ['Eritrea', 'er'],
  ['Eswatini', 'sz'],
  ['Ethiopië', 'et'],
  ['Gabon', 'ga'],
  ['Gambia', 'gm'],
  ['Ghana', 'gh'],
  ['Guinee', 'gn'],
  ['Guinee-Bissau', 'gw'],
  ['Ivoorkust', 'ci'],
  ['Kaapverdië', 'cv'],
  ['Kameroen', 'cm'],
  ['Kenia', 'ke'],
  ['Lesotho', 'ls'],
  ['Liberia', 'lr'],
  ['Libië', 'ly'],
  ['Madagaskar', 'mg'],
  ['Malawi', 'mw'],
  ['Mali', 'ml'],
  ['Marokko', 'ma'],
  ['Mauritanië', 'mr'],
  ['Mauritius', 'mu'],
  ['Mozambique', 'mz'],
  ['Namibië', 'na'],
  ['Niger', 'ne'],
  ['Nigeria', 'ng'],
  ['Oeganda', 'ug'],
  ['Rwanda', 'rw'],
  ['Sao Tomé en Principe', 'st'],
  ['Senegal', 'sn'],
  ['Seychellen', 'sc'],
  ['Sierra Leone', 'sl'],
  ['Soedan', 'sd'],
  ['Somalië', 'so'],
  ['Tanzania', 'tz'],
  ['Togo', 'tg'],
  ['Tsjaad', 'td'],
  ['Tunesië', 'tn'],
  ['Zambia', 'zm'],
  ['Zimbabwe', 'zw'],
  ['Zuid-Afrika', 'za'],
  ['Zuid-Soedan', 'ss'],
];

const azie = [
  ['Afghanistan', 'af'],
  ['Armenië', 'am'],
  ['Azerbeidzjan', 'az'],
  ['Bahrein', 'bh'],
  ['Bangladesh', 'bd'],
  ['Bhutan', 'bt'],
  ['Brunei', 'bn'],
  ['Cambodja', 'kh'],
  ['China', 'cn'],
  ['Filipijnen', 'ph'],
  ['Georgië', 'ge'],
  ['India', 'in'],
  ['Indonesië', 'id'],
  ['Irak', 'iq'],
  ['Iran', 'ir'],
  ['Israël', 'il'],
  ['Japan', 'jp'],
  ['Jemen', 'ye'],
  ['Jordanië', 'jo'],
  ['Kazachstan', 'kz'],
  ['Kirgizië', 'kg'],
  ['Koeweit', 'kw'],
  ['Laos', 'la'],
  ['Libanon', 'lb'],
  ['Maldiven', 'mv'],
  ['Maleisië', 'my'],
  ['Mongolië', 'mn'],
  ['Myanmar', 'mm'],
  ['Nepal', 'np'],
  ['Noord-Korea', 'kp'],
  ['Oezbekistan', 'uz'],
  ['Oman', 'om'],
  ['Oost-Timor', 'tl'],
  ['Pakistan', 'pk'],
  ['Qatar', 'qa'],
  ['Saudi-Arabië', 'sa'],
  ['Singapore', 'sg'],
  ['Sri Lanka', 'lk'],
  ['Syrië', 'sy'],
  ['Tadzjikistan', 'tj'],
  ['Thailand', 'th'],
  ['Turkije', 'tr'],
  ['Turkmenistan', 'tm'],
  ['Verenigde Arabische Emiraten', 'ae'],
  ['Vietnam', 'vn'],
  ['Zuid-Korea', 'kr'],
];

const noordAmerika = [
  ['Antigua en Barbuda', 'ag'],
  ["Bahama's", 'bs'],
  ['Barbados', 'bb'],
  ['Belize', 'bz'],
  ['Canada', 'ca'],
  ['Costa Rica', 'cr'],
  ['Cuba', 'cu'],
  ['Dominica', 'dm'],
  ['Dominicaanse Republiek', 'do'],
  ['El Salvador', 'sv'],
  ['Grenada', 'gd'],
  ['Guatemala', 'gt'],
  ['Haïti', 'ht'],
  ['Honduras', 'hn'],
  ['Jamaica', 'jm'],
  ['Mexico', 'mx'],
  ['Nicaragua', 'ni'],
  ['Panama', 'pa'],
  ['Saint Kitts en Nevis', 'kn'],
  ['Saint Lucia', 'lc'],
  ['Saint Vincent en de Grenadines', 'vc'],
  ['Trinidad en Tobago', 'tt'],
  ['Verenigde Staten', 'us'],
];

const zuidAmerika = [
  ['Argentinië', 'ar'],
  ['Bolivia', 'bo'],
  ['Brazilië', 'br'],
  ['Chili', 'cl'],
  ['Colombia', 'co'],
  ['Ecuador', 'ec'],
  ['Guyana', 'gy'],
  ['Paraguay', 'py'],
  ['Peru', 'pe'],
  ['Suriname', 'sr'],
  ['Uruguay', 'uy'],
  ['Venezuela', 've'],
];

const oceanie = [
  ['Australië', 'au'],
  ['Fiji', 'fj'],
  ['Kiribati', 'ki'],
  ['Marshalleilanden', 'mh'],
  ['Micronesia', 'fm'],
  ['Nauru', 'nr'],
  ['Nieuw-Zeeland', 'nz'],
  ['Palau', 'pw'],
  ['Papoea-Nieuw-Guinea', 'pg'],
  ['Salomonseilanden', 'sb'],
  ['Samoa', 'ws'],
  ['Tonga', 'to'],
  ['Tuvalu', 'tv'],
  ['Vanuatu', 'vu'],
];

const lists = [europa, afrika, azie, noordAmerika, zuidAmerika, oceanie];

export const items = lists.flatMap((list, i) =>
  list.map(([name, code]) => ({
    name,
    code,
    package: continents[i].id,
    continent: continents[i].name,
  })),
);
